service:
  cocktail: "db"
  shoppingList: "db"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #The SQL dialect makes Hibernate generate better SQL for the chosen database
        jdbc:
          lob:
            non-contextual-creation: true

# Actuator
management:
  endpoint:
    health:
      show-details: always

server:
  # http connector
  http:
    port: 8080
  # TLS settings
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/local-keystore.jks
    key-store-password: hunter2
    key-alias: localhost
    trust-store: classpath:keystore/local-truststore.jks
    trust-store-password: hunter2
    client-auth: need

# feign config
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000
        logger-level: basic

logging:
  level:
    "[com.ezgroceries.shoppinglist]": DEBUG
